### ISSUE TITLE
Practice0 Setup

### ISSUE THREAD

**Issue by tyvaughan** [fdac17/news#4]
I am unable to access the Practice0 assignment in my browser through localhost:8888 after cloning it remotely on da2.  Would this have anything to do with the localforward statement in the config file, and if so, could someone provide an example?  Thanks ahead of time for any help or feedback.

**Comment by audrism** [comment]
put the following in the .ss/config
```
 host da2
    hostname da2.eecs.utk.edu
    port YOURPORT #from students/ports.md
    username YOURNETID
    LocalForward 8888 127.0.0.1:8888
```
then access via 
```
ssh da2
```

or, alternatively,  via command line
```
ssh -p YOURPORT -L8888:127.0.0.1:8888 YOURNETID@da2.eecs.utk.edu
```

**Comment by paineleffler** [comment]
>  host da2
>     **hosthostname** da2.eecs.utk.edu
>     port YOURPORT **from students/ports.md**
>     **username** YOURNETID
>     LocalForward 8888 127.0.0.1:8888

"**hosthostname**" is a typo? Should just be "**HostName**" and "**from students/ports.md**" is not actually in the file. "**username**" should just be "**User**"

**Comment by audrism** [comment]
fixed
